// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (item_id, seller_id, starting_price, end_time, original_end_time, status)
VALUES ($1, $2, $3, $4, $4, 'active')
    RETURNING id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at
`

type CreateAuctionParams struct {
	ItemID        int64
	SellerID      int64
	StartingPrice int64
	EndTime       pgtype.Timestamptz
}

func (q *Queries) CreateAuction(ctx context.Context, arg *CreateAuctionParams) (*Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.ItemID,
		arg.SellerID,
		arg.StartingPrice,
		arg.EndTime,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getActiveAuctionByItem = `-- name: GetActiveAuctionByItem :one
SELECT id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at FROM auctions WHERE item_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveAuctionByItem(ctx context.Context, itemID int64) (*Auction, error) {
	row := q.db.QueryRow(ctx, getActiveAuctionByItem, itemID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuction = `-- name: GetAuction :one
SELECT id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at FROM auctions WHERE id = $1
`

func (q *Queries) GetAuction(ctx context.Context, id int64) (*Auction, error) {
	row := q.db.QueryRow(ctx, getAuction, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuctionForUpdate = `-- name: GetAuctionForUpdate :one
SELECT id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at FROM auctions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAuctionForUpdate(ctx context.Context, id int64) (*Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionForUpdate, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const listActiveAuctions = `-- name: ListActiveAuctions :many
SELECT id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at FROM auctions WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListActiveAuctions(ctx context.Context) ([]*Auction, error) {
	rows, err := q.db.Query(ctx, listActiveAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SellerID,
			&i.StartingPrice,
			&i.HighestBid,
			&i.HighestBidderID,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAuctions = `-- name: ListExpiredAuctions :many
SELECT id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at FROM auctions
WHERE status = 'active' AND end_time <= NOW()
`

func (q *Queries) ListExpiredAuctions(ctx context.Context) ([]*Auction, error) {
	rows, err := q.db.Query(ctx, listExpiredAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SellerID,
			&i.StartingPrice,
			&i.HighestBid,
			&i.HighestBidderID,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuctionBid = `-- name: UpdateAuctionBid :one
UPDATE auctions
SET highest_bid       = $2,
    highest_bidder_id = $3,
    end_time          = $4
WHERE id = $1
    RETURNING id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at
`

type UpdateAuctionBidParams struct {
	ID              int64
	HighestBid      int64
	HighestBidderID *int64
	EndTime         pgtype.Timestamptz
}

func (q *Queries) UpdateAuctionBid(ctx context.Context, arg *UpdateAuctionBidParams) (*Auction, error) {
	row := q.db.QueryRow(ctx, updateAuctionBid,
		arg.ID,
		arg.HighestBid,
		arg.HighestBidderID,
		arg.EndTime,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const updateAuctionStatus = `-- name: UpdateAuctionStatus :one
UPDATE auctions SET status = $2 WHERE id = $1 RETURNING id, item_id, seller_id, starting_price, highest_bid, highest_bidder_id, end_time, original_end_time, status, created_at
`

type UpdateAuctionStatusParams struct {
	ID     int64
	Status AuctionStatus
}

func (q *Queries) UpdateAuctionStatus(ctx context.Context, arg *UpdateAuctionStatusParams) (*Auction, error) {
	row := q.db.QueryRow(ctx, updateAuctionStatus, arg.ID, arg.Status)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.StartingPrice,
		&i.HighestBid,
		&i.HighestBidderID,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}
