// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bid.sql

package db

import (
	"context"
)

const cancelBid = `-- name: CancelBid :one
UPDATE bids SET is_cancelled = TRUE WHERE id = $1 RETURNING id, auction_id, guild_id, amount, is_cancelled, created_at
`

func (q *Queries) CancelBid(ctx context.Context, id int64) (*Bid, error) {
	row := q.db.QueryRow(ctx, cancelBid, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.GuildID,
		&i.Amount,
		&i.IsCancelled,
		&i.CreatedAt,
	)
	return &i, err
}

const createBid = `-- name: CreateBid :one
INSERT INTO bids (auction_id, guild_id, amount)
VALUES ($1, $2, $3)
    RETURNING id, auction_id, guild_id, amount, is_cancelled, created_at
`

type CreateBidParams struct {
	AuctionID int64
	GuildID   int64
	Amount    int64
}

func (q *Queries) CreateBid(ctx context.Context, arg *CreateBidParams) (*Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.AuctionID, arg.GuildID, arg.Amount)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.GuildID,
		&i.Amount,
		&i.IsCancelled,
		&i.CreatedAt,
	)
	return &i, err
}

const getBid = `-- name: GetBid :one
SELECT id, auction_id, guild_id, amount, is_cancelled, created_at FROM bids WHERE id = $1
`

func (q *Queries) GetBid(ctx context.Context, id int64) (*Bid, error) {
	row := q.db.QueryRow(ctx, getBid, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.GuildID,
		&i.Amount,
		&i.IsCancelled,
		&i.CreatedAt,
	)
	return &i, err
}

const listActiveBidsByGuildAndAuction = `-- name: ListActiveBidsByGuildAndAuction :many
SELECT id, auction_id, guild_id, amount, is_cancelled, created_at FROM bids
WHERE auction_id = $1 AND guild_id = $2 AND is_cancelled = FALSE
ORDER BY amount DESC
`

type ListActiveBidsByGuildAndAuctionParams struct {
	AuctionID int64
	GuildID   int64
}

func (q *Queries) ListActiveBidsByGuildAndAuction(ctx context.Context, arg *ListActiveBidsByGuildAndAuctionParams) ([]*Bid, error) {
	rows, err := q.db.Query(ctx, listActiveBidsByGuildAndAuction, arg.AuctionID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.GuildID,
			&i.Amount,
			&i.IsCancelled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidsByAuction = `-- name: ListBidsByAuction :many
SELECT id, auction_id, guild_id, amount, is_cancelled, created_at FROM bids
WHERE auction_id = $1 AND is_cancelled = FALSE
ORDER BY amount DESC
`

func (q *Queries) ListBidsByAuction(ctx context.Context, auctionID int64) ([]*Bid, error) {
	rows, err := q.db.Query(ctx, listBidsByAuction, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.GuildID,
			&i.Amount,
			&i.IsCancelled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
