// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild.sql

package db

import (
	"context"
)

const getGuild = `-- name: GetGuild :one
SELECT id, name, total_money, reserved_money, daily_limit, daily_spent FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id int64) (*Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const getGuildForUpdate = `-- name: GetGuildForUpdate :one
SELECT id, name, total_money, reserved_money, daily_limit, daily_spent FROM guilds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetGuildForUpdate(ctx context.Context, id int64) (*Guild, error) {
	row := q.db.QueryRow(ctx, getGuildForUpdate, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const resetDailySpent = `-- name: ResetDailySpent :exec
UPDATE guilds SET daily_spent = 0
`

func (q *Queries) ResetDailySpent(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDailySpent)
	return err
}

const updateGuildWallet = `-- name: UpdateGuildWallet :one
UPDATE guilds
SET total_money    = $2,
    reserved_money = $3,
    daily_spent    = $4
WHERE id = $1
    RETURNING id, name, total_money, reserved_money, daily_limit, daily_spent
`

type UpdateGuildWalletParams struct {
	ID            int64
	TotalMoney    int64
	ReservedMoney int64
	DailySpent    int64
}

func (q *Queries) UpdateGuildWallet(ctx context.Context, arg *UpdateGuildWalletParams) (*Guild, error) {
	row := q.db.QueryRow(ctx, updateGuildWallet,
		arg.ID,
		arg.TotalMoney,
		arg.ReservedMoney,
		arg.DailySpent,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}
