// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package db

import (
	"context"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (item_id, seller_id, price, status, updated_at)
VALUES ($1, $2, $3, 'active', NOW())
    RETURNING id, item_id, seller_id, buyer_id, price, status, created_at, updated_at
`

type CreateListingParams struct {
	ItemID   int64
	SellerID int64
	Price    int64
}

func (q *Queries) CreateListing(ctx context.Context, arg *CreateListingParams) (*Listing, error) {
	row := q.db.QueryRow(ctx, createListing, arg.ItemID, arg.SellerID, arg.Price)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.BuyerID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getListing = `-- name: GetListing :one
SELECT id, item_id, seller_id, buyer_id, price, status, created_at, updated_at FROM listings WHERE id = $1
`

func (q *Queries) GetListing(ctx context.Context, id int64) (*Listing, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.BuyerID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getListingForUpdate = `-- name: GetListingForUpdate :one
SELECT id, item_id, seller_id, buyer_id, price, status, created_at, updated_at FROM listings WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetListingForUpdate(ctx context.Context, id int64) (*Listing, error) {
	row := q.db.QueryRow(ctx, getListingForUpdate, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.BuyerID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listActiveListings = `-- name: ListActiveListings :many
SELECT id, item_id, seller_id, buyer_id, price, status, created_at, updated_at FROM listings WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListActiveListings(ctx context.Context) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, listActiveListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SellerID,
			&i.BuyerID,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListingStatus = `-- name: UpdateListingStatus :one
UPDATE listings
SET status = $2, buyer_id = $3, updated_at = NOW()
WHERE id = $1
    RETURNING id, item_id, seller_id, buyer_id, price, status, created_at, updated_at
`

type UpdateListingStatusParams struct {
	ID      int64
	Status  ListingStatus
	BuyerID *int64
}

func (q *Queries) UpdateListingStatus(ctx context.Context, arg *UpdateListingStatusParams) (*Listing, error) {
	row := q.db.QueryRow(ctx, updateListingStatus, arg.ID, arg.Status, arg.BuyerID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.BuyerID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
