// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuctionStatus string

const (
	AuctionStatusActive    AuctionStatus = "active"
	AuctionStatusFinished  AuctionStatus = "finished"
	AuctionStatusCancelled AuctionStatus = "cancelled"
)

func (e *AuctionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionStatus(s)
	case string:
		*e = AuctionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionStatus: %T", src)
	}
	return nil
}

type NullAuctionStatus struct {
	AuctionStatus AuctionStatus
	Valid         bool // Valid is true if AuctionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionStatus), nil
}

func (e AuctionStatus) Valid() bool {
	switch e {
	case AuctionStatusActive,
		AuctionStatusFinished,
		AuctionStatusCancelled:
		return true
	}
	return false
}

func AllAuctionStatusValues() []AuctionStatus {
	return []AuctionStatus{
		AuctionStatusActive,
		AuctionStatusFinished,
		AuctionStatusCancelled,
	}
}

type ItemStatus string

const (
	ItemStatusAvailable ItemStatus = "available"
	ItemStatusListed    ItemStatus = "listed"
	ItemStatusAuctioned ItemStatus = "auctioned"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

func (e ItemStatus) Valid() bool {
	switch e {
	case ItemStatusAvailable,
		ItemStatusListed,
		ItemStatusAuctioned:
		return true
	}
	return false
}

func AllItemStatusValues() []ItemStatus {
	return []ItemStatus{
		ItemStatusAvailable,
		ItemStatusListed,
		ItemStatusAuctioned,
	}
}

type ItemType string

const (
	ItemTypeCommon    ItemType = "common"
	ItemTypeRare      ItemType = "rare"
	ItemTypeLegendary ItemType = "legendary"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

func (e ItemType) Valid() bool {
	switch e {
	case ItemTypeCommon,
		ItemTypeRare,
		ItemTypeLegendary:
		return true
	}
	return false
}

func AllItemTypeValues() []ItemType {
	return []ItemType{
		ItemTypeCommon,
		ItemTypeRare,
		ItemTypeLegendary,
	}
}

type ListingStatus string

const (
	ListingStatusActive    ListingStatus = "active"
	ListingStatusSold      ListingStatus = "sold"
	ListingStatusCancelled ListingStatus = "cancelled"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus
	Valid         bool // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

func (e ListingStatus) Valid() bool {
	switch e {
	case ListingStatusActive,
		ListingStatusSold,
		ListingStatusCancelled:
		return true
	}
	return false
}

func AllListingStatusValues() []ListingStatus {
	return []ListingStatus{
		ListingStatusActive,
		ListingStatusSold,
		ListingStatusCancelled,
	}
}

type RefType string

const (
	RefTypeAuction RefType = "auction"
	RefTypeListing RefType = "listing"
	RefTypeTrade   RefType = "trade"
)

func (e *RefType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefType(s)
	case string:
		*e = RefType(s)
	default:
		return fmt.Errorf("unsupported scan type for RefType: %T", src)
	}
	return nil
}

type NullRefType struct {
	RefType RefType
	Valid   bool // Valid is true if RefType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefType) Scan(value interface{}) error {
	if value == nil {
		ns.RefType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefType), nil
}

func (e RefType) Valid() bool {
	switch e {
	case RefTypeAuction,
		RefTypeListing,
		RefTypeTrade:
		return true
	}
	return false
}

func AllRefTypeValues() []RefType {
	return []RefType{
		RefTypeAuction,
		RefTypeListing,
		RefTypeTrade,
	}
}

type TradeType string

const (
	TradeTypeAuction TradeType = "auction"
	TradeTypeListing TradeType = "listing"
)

func (e *TradeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradeType(s)
	case string:
		*e = TradeType(s)
	default:
		return fmt.Errorf("unsupported scan type for TradeType: %T", src)
	}
	return nil
}

type NullTradeType struct {
	TradeType TradeType
	Valid     bool // Valid is true if TradeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradeType) Scan(value interface{}) error {
	if value == nil {
		ns.TradeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradeType), nil
}

func (e TradeType) Valid() bool {
	switch e {
	case TradeTypeAuction,
		TradeTypeListing:
		return true
	}
	return false
}

func AllTradeTypeValues() []TradeType {
	return []TradeType{
		TradeTypeAuction,
		TradeTypeListing,
	}
}

type TxType string

const (
	TxTypeReserve TxType = "reserve"
	TxTypeRelease TxType = "release"
	TxTypeDebit   TxType = "debit"
	TxTypeCredit  TxType = "credit"
)

func (e *TxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxType(s)
	case string:
		*e = TxType(s)
	default:
		return fmt.Errorf("unsupported scan type for TxType: %T", src)
	}
	return nil
}

type NullTxType struct {
	TxType TxType
	Valid  bool // Valid is true if TxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxType) Scan(value interface{}) error {
	if value == nil {
		ns.TxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxType), nil
}

func (e TxType) Valid() bool {
	switch e {
	case TxTypeReserve,
		TxTypeRelease,
		TxTypeDebit,
		TxTypeCredit:
		return true
	}
	return false
}

func AllTxTypeValues() []TxType {
	return []TxType{
		TxTypeReserve,
		TxTypeRelease,
		TxTypeDebit,
		TxTypeCredit,
	}
}

type Auction struct {
	ID              int64
	ItemID          int64
	SellerID        int64
	StartingPrice   int64
	HighestBid      int64
	HighestBidderID *int64
	EndTime         pgtype.Timestamptz
	OriginalEndTime pgtype.Timestamptz
	Status          AuctionStatus
	CreatedAt       pgtype.Timestamptz
}

type Bid struct {
	ID          int64
	AuctionID   int64
	GuildID     int64
	Amount      int64
	IsCancelled bool
	CreatedAt   pgtype.Timestamptz
}

type Guild struct {
	ID            int64
	Name          string
	TotalMoney    int64
	ReservedMoney int64
	DailyLimit    int64
	DailySpent    int64
}

type Item struct {
	ID      int64
	Name    string
	Type    ItemType
	Status  ItemStatus
	OwnerID int64
}

type Listing struct {
	ID        int64
	ItemID    int64
	SellerID  int64
	BuyerID   *int64
	Price     int64
	Status    ListingStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Trade struct {
	ID        int64
	ItemID    int64
	SellerID  int64
	BuyerID   int64
	Price     int64
	Type      TradeType
	CreatedAt pgtype.Timestamptz
}

type WalletTransaction struct {
	ID        int64
	GuildID   int64
	Type      TxType
	Amount    int64
	RefType   RefType
	RefID     int64
	CreatedAt pgtype.Timestamptz
}
