// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade.sql

package db

import (
	"context"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (item_id, seller_id, buyer_id, price, type)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, item_id, seller_id, buyer_id, price, type, created_at
`

type CreateTradeParams struct {
	ItemID   int64
	SellerID int64
	BuyerID  int64
	Price    int64
	Type     TradeType
}

func (q *Queries) CreateTrade(ctx context.Context, arg *CreateTradeParams) (*Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.ItemID,
		arg.SellerID,
		arg.BuyerID,
		arg.Price,
		arg.Type,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.BuyerID,
		&i.Price,
		&i.Type,
		&i.CreatedAt,
	)
	return &i, err
}

const listTradesByGuild = `-- name: ListTradesByGuild :many
SELECT id, item_id, seller_id, buyer_id, price, type, created_at FROM trades
WHERE seller_id = $1 OR buyer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTradesByGuild(ctx context.Context, sellerID int64) ([]*Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByGuild, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SellerID,
			&i.BuyerID,
			&i.Price,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
