// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (guild_id, type, amount, ref_type, ref_id)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, guild_id, type, amount, ref_type, ref_id, created_at
`

type CreateWalletTransactionParams struct {
	GuildID int64
	Type    TxType
	Amount  int64
	RefType RefType
	RefID   int64
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg *CreateWalletTransactionParams) (*WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.GuildID,
		arg.Type,
		arg.Amount,
		arg.RefType,
		arg.RefID,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.Amount,
		&i.RefType,
		&i.RefID,
		&i.CreatedAt,
	)
	return &i, err
}

const getDailySpent = `-- name: GetDailySpent :one
SELECT COALESCE(SUM(amount), 0)::BIGINT FROM wallet_transactions
WHERE guild_id = $1
  AND type = 'reserve'
  AND created_at >= NOW()::DATE
`

func (q *Queries) GetDailySpent(ctx context.Context, guildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDailySpent, guildID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, guild_id, type, amount, ref_type, ref_id, created_at FROM wallet_transactions
WHERE guild_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWalletTransactions(ctx context.Context, guildID int64) ([]*WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Type,
			&i.Amount,
			&i.RefType,
			&i.RefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
